controller_manager:
  ros__parameters:
    update_rate: 10
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    use_sim_time: true
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.25
    wheel_radius: 0.05
    base_frame_id: base_footprint
    odom_frame_id: odom
    enable_odom_tf: true
    cmd_vel_timeout: 0.5
    publish_rate: 30
    use_stamped_vel: true
